-- MySQL Script generated by MySQL Workbench
-- Mon Jun 26 23:44:28 2017
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema instalacoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema instalacoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `instalacoes` ;
USE `instalacoes` ;

-- -----------------------------------------------------
-- Table `instalacoes`.`Metodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`Metodo` (
  `idMetodo` INT NOT NULL,
  `tipo` VARCHAR(4) NULL,
  `descricao` VARCHAR(120) NULL,
  PRIMARY KEY (`idMetodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`Materiais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`Materiais` (
  `idMaterial` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`idMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`Isolante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`Isolante` (
  `idIsolante` INT NOT NULL,
  `idMaterialIsolante` INT NOT NULL,
  PRIMARY KEY (`idIsolante`),
  INDEX `fk_Isolante_Materiais1_idx` (`idMaterialIsolante` ASC),
  CONSTRAINT `fk_Isolante_Materiais1`
    FOREIGN KEY (`idMaterialIsolante`)
    REFERENCES `instalacoes`.`Materiais` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`Cabos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`Cabos` (
  `idCabo` INT NOT NULL,
  `idMaterialCabo` INT NOT NULL,
  `diametro` FLOAT NULL,
  INDEX `fk_Cabos_Materiais1_idx` (`idMaterialCabo` ASC),
  PRIMARY KEY (`idCabo`),
  CONSTRAINT `fk_Cabos_Materiais1`
    FOREIGN KEY (`idMaterialCabo`)
    REFERENCES `instalacoes`.`Materiais` (`idMaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`CapacidadeConducao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`CapacidadeConducao` (
  `idCapacidade` INT NOT NULL AUTO_INCREMENT,
  `idMetodo` INT NOT NULL,
  `idCabo` INT NOT NULL,
  `idIsolante` INT NOT NULL,
  `n2Conector` INT NULL,
  `n3Conector` INT NULL,
  INDEX `fk_CapacidadeConducao_Metodo1_idx` (`idMetodo` ASC),
  INDEX `fk_CapacidadeConducao_Cabos1_idx` (`idCabo` ASC),
  INDEX `fk_CapacidadeConducao_Isolante1_idx` (`idIsolante` ASC),
  PRIMARY KEY (`idCapacidade`),
  CONSTRAINT `fk_CapacidadeConducao_Metodo1`
    FOREIGN KEY (`idMetodo`)
    REFERENCES `instalacoes`.`Metodo` (`idMetodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CapacidadeConducao_Cabos1`
    FOREIGN KEY (`idCabo`)
    REFERENCES `instalacoes`.`Cabos` (`idCabo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CapacidadeConducao_Isolante1`
    FOREIGN KEY (`idIsolante`)
    REFERENCES `instalacoes`.`Isolante` (`idIsolante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`Correcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`Correcao` (
  `idCorrecao` INT NOT NULL,
  `tipo` VARCHAR(10) NULL,
  PRIMARY KEY (`idCorrecao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`K1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`K1` (
  `idK1` INT NOT NULL,
  `idTipo` INT NOT NULL,
  `idIsolante` INT NOT NULL,
  `temperatura` INT NULL,
  `isolante` FLOAT NULL,
  INDEX `fk_K1_Correcao1_idx` (`idTipo` ASC),
  PRIMARY KEY (`idK1`),
  CONSTRAINT `fk_K1_Correcao1`
    FOREIGN KEY (`idTipo`)
    REFERENCES `instalacoes`.`Correcao` (`idCorrecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_K1_Isolante1`
    FOREIGN KEY (`idIsolante`)
    REFERENCES `instalacoes`.`Isolante` (`idIsolante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`K2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`K2` (
  `idK2` INT NOT NULL,
  `resTermica` INT NULL,
  `fatorCorrecao` FLOAT NULL,
  PRIMARY KEY (`idK2`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`K3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`K3` (
  `idK3` INT NOT NULL,
  `descricao` VARCHAR(60) NULL,
  `n1` FLOAT NULL,
  `n2` FLOAT NULL,
  `n3` FLOAT NULL,
  `n4` FLOAT NULL,
  `n5` FLOAT NULL,
  `n6` FLOAT NULL,
  `n7` FLOAT NULL,
  `n8` FLOAT NULL,
  `n9` FLOAT NULL,
  `n12` FLOAT NULL,
  `n16` FLOAT NULL,
  `n20` FLOAT NULL,
  PRIMARY KEY (`idK3`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`ResistenciaReatanciaCabos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`ResistenciaReatanciaCabos` (
  `idResistenciaReatancia` INT NOT NULL AUTO_INCREMENT,
  `idCabo` INT NOT NULL,
  `rcc` FLOAT NULL,
  `rca` FLOAT NULL,
  `xl` FLOAT NULL,
  PRIMARY KEY (`idResistenciaReatancia`),
  INDEX `fk_ResistenciaReatancia_Cabos1_idx` (`idCabo` ASC),
  CONSTRAINT `fk_ResistenciaReatancia_Cabos1`
    FOREIGN KEY (`idCabo`)
    REFERENCES `instalacoes`.`Cabos` (`idCabo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`CorrenteCurtoCircuito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`CorrenteCurtoCircuito` (
  `idCorrenteCurtoCircuito` INT NOT NULL AUTO_INCREMENT,
  `potencia` FLOAT NULL,
  `correnteCurto1` FLOAT NULL,
  `correnteCurto2` FLOAT NULL,
  PRIMARY KEY (`idCorrenteCurtoCircuito`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`Tensao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`Tensao` (
  `idTensao` INT NOT NULL AUTO_INCREMENT,
  `tensao` VARCHAR(10) NULL,
  PRIMARY KEY (`idTensao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`CCurtoPresumida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`CCurtoPresumida` (
  `idCCurtoPresumida` INT NOT NULL AUTO_INCREMENT,
  `idTensao` INT NOT NULL,
  `idCabo` INT NOT NULL,
  `nCabo` INT NULL,
  `n1` FLOAT NULL,
  `n2` FLOAT NULL,
  `n3` FLOAT NULL,
  `n4` FLOAT NULL,
  `n5` FLOAT NULL,
  `n6` FLOAT NULL,
  `n7` FLOAT NULL,
  `n8` FLOAT NULL,
  `n9` FLOAT NULL,
  `n10` FLOAT NULL,
  `n11` FLOAT NULL,
  `n12` FLOAT NULL,
  `n13` FLOAT NULL,
  `n14` FLOAT NULL,
  `n15` FLOAT NULL,
  `n16` FLOAT NULL,
  `n17` FLOAT NULL,
  `n18` FLOAT NULL,
  `n19` FLOAT NULL,
  `n20` FLOAT NULL,
  `n21` FLOAT NULL,
  `n22` FLOAT NULL,
  `n23` FLOAT NULL,
  `n24` FLOAT NULL,
  PRIMARY KEY (`idCCurtoPresumida`),
  INDEX `fk_CCurtoPresumida_Tensao1_idx` (`idTensao` ASC),
  INDEX `fk_CCurtoPresumida_Cabos1_idx` (`idCabo` ASC),
  CONSTRAINT `fk_CCurtoPresumida_Tensao1`
    FOREIGN KEY (`idTensao`)
    REFERENCES `instalacoes`.`Tensao` (`idTensao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CCurtoPresumida_Cabos1`
    FOREIGN KEY (`idCabo`)
    REFERENCES `instalacoes`.`Cabos` (`idCabo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`CCNivelConsiderado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`CCNivelConsiderado` (
  `idCCNivelConsiderado` INT NOT NULL AUTO_INCREMENT,
  `CorrCCaMontante` INT NULL,
  `n1` FLOAT NULL,
  `n2` FLOAT NULL,
  `n3` FLOAT NULL,
  `n4` FLOAT NULL,
  `n5` FLOAT NULL,
  `n6` FLOAT NULL,
  `n7` FLOAT NULL,
  `n8` FLOAT NULL,
  `n9` FLOAT NULL,
  `n10` FLOAT NULL,
  `n11` FLOAT NULL,
  `n12` FLOAT NULL,
  `n13` FLOAT NULL,
  `n14` FLOAT NULL,
  `n15` FLOAT NULL,
  `n16` FLOAT NULL,
  `n17` FLOAT NULL,
  `n18` FLOAT NULL,
  `n19` FLOAT NULL,
  `n20` FLOAT NULL,
  `n21` FLOAT NULL,
  `n22` FLOAT NULL,
  `n23` FLOAT NULL,
  `n24` FLOAT NULL,
  PRIMARY KEY (`idCCNivelConsiderado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`Dijuntores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`Dijuntores` (
  `idDijuntores` INT NOT NULL AUTO_INCREMENT,
  `INominal` INT NULL,
  `curva` VARCHAR(4) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`idDijuntores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `instalacoes`.`NiveiCurtoCircuito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instalacoes`.`NiveiCurtoCircuito` (
  `idNiveiCurtoCircuito` INT NOT NULL AUTO_INCREMENT,
  `idTensao` INT NOT NULL,
  `snKVA` FLOAT NULL,
  `iKoKa` FLOAT NULL,
  PRIMARY KEY (`idNiveiCurtoCircuito`),
  INDEX `fk_NiveiCurtoCircuito_Tensao1_idx` (`idTensao` ASC),
  CONSTRAINT `fk_NiveiCurtoCircuito_Tensao1`
    FOREIGN KEY (`idTensao`)
    REFERENCES `instalacoes`.`Tensao` (`idTensao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
